### ISSUE TITLE
Bug: Content Filter Option Breaks Filter Flow

### ISSUE THREAD

**Issue by archetyped** [baden03/collapse-o-matic#4]
Hi,

This plugin breaks WordPress' `the_content` filter process when the "Content Filter" option is enabled.  

WordPress does not currently support nested filter calls of currently-running filter (e.g. applying `the_content` filters within a function hooked into `the_content`.  Since shortcodes (such as this plugin's `[expand]` shortcode) are processed in the `the_content` hook, applying the `the_content` hook within the shortcode handler steamrolls the already-running filter process and stops all other functions hooked into that filter from running.

To avoid this, the existing filter state needs to be temporarily saved before calling a nested `the_content`, and then restored once the nested filter call has finished.  Take a look at apply_filters() code for more details on its inner workings, and [see here for details on an example of backing up the filter state](https://github.com/websharks/wp-snippets/pull/2) in another shortcode that was inadvertently stopping plugins hooked into the `the_content` filter from running.

**Comment by baden03** [comment]
is this also an issue when 'apply filter' is _not_ checked in the plugin settings?

**Comment by baden03** [comment]
Issue closed
