### ISSUE TITLE
Reader view

### ISSUE THREAD

**Issue by antipole2** [baden03/collapse-o-matic#7]
Love the plugin.  Thanks.

In Safari (and probably other browsers too) there is a 'reader view' available on many pages, which does not display stuff like sidebars - just the hub o the page.  In reader view expand/collapse does nothing.  Is this unavoidable?

See the 'reading list' on [this page](https://mariannefrylectures.uk/past-lectures/2018-faisal-mahmood-jihad-therapy-room/).

**Comment by baden03** [comment]
Support for this plugin is only offered on the WordPress Forums:
https://wordpress.org/support/plugin/jquery-collapse-o-matic
